#!/usr/bin/env bash
set -euo pipefail

required=(DROPLET_IP APP_KEY DOMAIN_NAME)
for name in "${required[@]}"; do
  if [[ -z "${!name:-}" ]]; then
    echo "Missing required CI variable: $name" >&2
    exit 1
  fi
done

DB_CONNECTION="${DB_CONNECTION:-pgsql}"
if [[ "$DB_CONNECTION" == "pgsql" && -z "${DB_PASSWORD:-}" ]]; then
  echo "Missing required CI secret: DB_PASSWORD is required for PostgreSQL production." >&2
  exit 1
fi

DEPLOY_USER="${DEPLOY_USER:-root}"
DEPLOY_PATH="${DEPLOY_PATH:-/var/www/mercury-editions}"
tmp_env="$(mktemp)"
trap 'rm -f "$tmp_env"' EXIT

cat > "$tmp_env" <<EOF
APP_NAME="${APP_NAME:-Mercury Editions}"
APP_ENV=production
APP_KEY=${APP_KEY}
APP_DEBUG=false
APP_URL=https://${DOMAIN_NAME}
APP_TIMEZONE=${APP_TIMEZONE:-UTC}
APP_LOCALE=${APP_LOCALE:-fr}
APP_FALLBACK_LOCALE=${APP_FALLBACK_LOCALE:-fr}
APP_FAKER_LOCALE=${APP_FAKER_LOCALE:-fr_FR}

LOG_CHANNEL=${LOG_CHANNEL:-daily}
LOG_LEVEL=${LOG_LEVEL:-warning}

DB_CONNECTION=${DB_CONNECTION}
DB_DATABASE=${DB_DATABASE:-mercury}
DB_HOST=${DB_HOST:-127.0.0.1}
DB_PORT=${DB_PORT:-5432}
DB_USERNAME=${DB_USERNAME:-mercury}
DB_PASSWORD=${DB_PASSWORD:-}

SESSION_DRIVER=${SESSION_DRIVER:-redis}
SESSION_LIFETIME=${SESSION_LIFETIME:-120}
SESSION_ENCRYPT=true
SESSION_PATH=/
SESSION_DOMAIN=${SESSION_DOMAIN:-null}
SESSION_SECURE_COOKIE=true
SESSION_SAME_SITE=${SESSION_SAME_SITE:-lax}

BROADCAST_CONNECTION=${BROADCAST_CONNECTION:-log}
FILESYSTEM_DISK=${FILESYSTEM_DISK:-local}
QUEUE_CONNECTION=${QUEUE_CONNECTION:-redis}
CACHE_STORE=${CACHE_STORE:-redis}

REDIS_CLIENT=${REDIS_CLIENT:-phpredis}
REDIS_HOST=${REDIS_HOST:-127.0.0.1}
REDIS_PASSWORD=${REDIS_PASSWORD:-null}
REDIS_PORT=${REDIS_PORT:-6379}

MAIL_MAILER=${MAIL_MAILER:-smtp}
MAIL_SCHEME=${MAIL_SCHEME:-null}
MAIL_HOST=${MAIL_HOST:-}
MAIL_PORT=${MAIL_PORT:-587}
MAIL_USERNAME=${MAIL_USERNAME:-}
MAIL_PASSWORD=${MAIL_PASSWORD:-}
MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS:-contact@mercury-editions.bf}
MAIL_FROM_NAME="${MAIL_FROM_NAME:-Mercury Editions}"

MERCURY_EDITORIAL_EMAIL=${MERCURY_EDITORIAL_EMAIL:-manuscrits@mercury-editions.bf}

ORANGE_OM_SIMULATE=${ORANGE_OM_SIMULATE:-false}
ORANGE_OM_ENV=${ORANGE_OM_ENV:-prod}
ORANGE_COUNTRY_CODE=${ORANGE_COUNTRY_CODE:-226}
ORANGE_OM_URL_PROD=${ORANGE_OM_URL_PROD:-https://apiom.orange.bf/}
ORANGE_OM_URL_TEST=${ORANGE_OM_URL_TEST:-https://testom.orange.bf/}
ORANGE_OM_MERCHANT_MSISDN=${ORANGE_OM_MERCHANT_MSISDN:-}
ORANGE_OM_API_USERNAME=${ORANGE_OM_API_USERNAME:-}
ORANGE_OM_API_PASSWORD=${ORANGE_OM_API_PASSWORD:-}
ORANGE_OM_PROVIDER=${ORANGE_OM_PROVIDER:-101}
ORANGE_OM_PROVIDER2=${ORANGE_OM_PROVIDER2:-101}
ORANGE_OM_PAYID=${ORANGE_OM_PAYID:-12}
ORANGE_OM_PAYID2=${ORANGE_OM_PAYID2:-12}

AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
AWS_BUCKET=${AWS_BUCKET:-}
AWS_USE_PATH_STYLE_ENDPOINT=${AWS_USE_PATH_STYLE_ENDPOINT:-false}

VITE_APP_NAME="${APP_NAME:-Mercury Editions}"
CORS_ALLOWED_ORIGINS=https://${DOMAIN_NAME}
EOF

scp "$tmp_env" "$DEPLOY_USER@$DROPLET_IP:$DEPLOY_PATH/shared/.env.tmp"
ssh "$DEPLOY_USER@$DROPLET_IP" "mv '$DEPLOY_PATH/shared/.env.tmp' '$DEPLOY_PATH/shared/.env' && chmod 600 '$DEPLOY_PATH/shared/.env'"

echo "Remote production environment written."
